### ISSUE TITLE
[scrap_allmusic] crash with /louis-spohr-octet-nonet-clarinet-concerto-mw0002845017

### ISSUE THREAD

**Issue by antvig** [antvig/JazzExplorer#12]
while parsing `/louis-spohr-octet-nonet-clarinet-concerto-mw0002845017`

```  
Traceback (most recent call last):
  File "C:/Users/SESA408771/Documents/03_Repo/project/JazzExplorer/scripts/scrap_allmusic.py", line 81, in <module>
    album_info, new_artist_url, new_artist_to_album = scrap_album_page(album_soup, album_url)
  File "C:\Users\SESA408771\Documents\03_Repo\project\JazzExplorer\src\web_scrapping\allmusic.py", line 133, in scrap_album_page
    artist_url, artist_to_album = get_artists_of_album_url(soup, url, album_info['name'])
  File "C:\Users\SESA408771\Documents\03_Repo\project\JazzExplorer\src\web_scrapping\allmusic.py", line 105, in get_artists_of_album_url
    artist_url = artist_col.find('a')['href'].replace('https://www.allmusic.com/artist', '')
TypeError: 'NoneType' object is not subscriptable

```

**Comment by antvig** [comment]
artist `/colin-davis-mn0000081839`
